### PR TITLE
Feature/review 1 fixes

### LINKED ISSUE #1: Review
The code looks overall very good, readable, with comments. I think it is not common to have public actor code looks clean like this 👍 
Just a few notes, which I found:
- const should be at the begging of the file, to better readability https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/src/utils.js#L26 (same for ERROR_TYPES const) 
- You can even get just open position from API with /jobs/status/open https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/src/worker.js#L31
- You can use sleep helper from sdk https://sdk.apify.com/docs/api/utils#utilssleepmillis -> https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/src/worker.js#L144
- Maybe use some specific name for the state store of the actor. 'state' is quite generic and can have some collision with other actors https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/main.js#L15
- You ignore all errors coming from actor https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/main.js#L48 and you just log them, it is not a good approach. The actor should end up in a failed state if an unexpected issue happens.
- For logging you can use apify logger https://sdk.apify.com/docs/api/log, you can set debug logs, but it is optional

### PR DESCRIPTION
**Pull request by monkey-denky**

### CODE REVIEW

File: main.js [hunk 1]
```diff
@@ -5,46 +5,57 @@
...
 
   const worker = await Worker.create(startupJobsToken, jazzHRToken);
   const { items: stateRecords } = await dataset.getData();
 
   try {
     // Initialize values from state
+    log.info('Initiate state');
     const initialRecords = await worker.getNewRecords(stateRecords);
     await dataset.pushData(initialRecords);
     const { items: initializedRecords } = await dataset.getData();
```
Comment (jbartadev) [inline main.js:29]: Is it necessary to fetch the data from the dataset if you already have it?

File: main.js [hunk 2]
```diff
@@ -5,46 +5,57 @@
...
-    if (postable.length > 0) await store.setValue('LAST_APPLICATION', postable[0]);
-
-    const stats = {
-      totalRecords: initializedRecords.length + newRecords.length,
-      postableApplications: postable.length,
-      unresolvedErrors: remainingPostErrors.length + newPostErrors.length,
-    };
-    console.log('Stats: ', stats);
+    await store.setValue('RESOLVABLE_ERRORS', remainingPostErrors);
+    if (postable.length > 0) [lastApplication] = postable;
```
Comment (jbartadev) [inline main.js]: You can use `if (postable.length) ...`

Comment (jbartadev) [reply main.js]: same thing in `JazzHRClient.js` for `applicants2JobsList` method, also you can use `page++`; instead of `page + 1` there. (Can't comment if there isn't anything new)

Comment (jbartadev) [reply main.js]: In `applicantsWithDetails` there is a `concurrency: 30` maybe add the number to constants when you already have the whole file for that (ideally no hard-coded number in code)

Comment (jbartadev) [reply main.js]: The same is in `applicationsWithDetails` method in `startupJobsClient.js ` file, but the concurrency is lower, maybe unify this with one constant?

File: src/utils.js [hunk 3]
```diff
@@ -102,23 +100,20 @@ class ApplicationTransformer {
...
-  CREATE_NOTE: 'CREATE_NOTE',
-};
-
 module.exports = {
   stringToKey,
   splitFullname,
   ApplicationTransformer,
   parseStartupJobsIdFromJazzHR,
-  ERROR_TYPES,
+  htmlToText,
```
Comment (jbartadev) [inline src/utils.js:125]: Maybe add something like `bufferToString` to utils and use it in `getBase64Attachment` method to make it nicer.

File: src/worker.js [hunk 4]
```diff
@@ -26,9 +27,8 @@ class Worker {
   static async create(startupJobsToken, jazzHrToken) {
     const startupJobs = new StartupJobsClient(startupJobsToken);
     const jazzHR = new JazzHRClient(jazzHrToken);
-    const jobs = await jazzHR.jobList();
+    const jobs = await jazzHR.openJobList();
```
Comment (jbartadev) [inline src/worker.js:32]: The switch is not necessary in `resolvePostErrors` method with just variant right?

Comment (jbartadev) [reply src/worker.js:32]: also hard-coded `sleep` and `concurrency` on few places

**Review by jbartadev — CHANGES_REQUESTED** [review]
Looks good, small improvements & changes

File: main.js (hunk 1 above)
Comment (monkey-denky) [reply main.js:29]: on line 28 I update the dataset and I it with updated values

File: main.js (hunk 2 above)
Comment (monkey-denky) [reply main.js]: I use default airbnb linting rules which prohibits page++ .. I was too lazy to override the rule so I just left it like that .. As for concurrency I will create constants but there will have to be 2 separate ones for startupjobs and jazzHR since their APIs react differently

File: src/worker.js (hunk 4 above)
Comment (monkey-denky) [reply src/worker.js:32]: Lets leave the switch just in case I add more error types in the future.. I will create constants for both sleep and concurrency

File: src/utils.js (hunk 3 above)
Comment (monkey-denky) [reply src/utils.js:125]: Good point will do

**Review by jbartadev — APPROVED** [review]
Looks good, let's see how it's going to work 😄

**Review by drobnikj — APPROVED** [review]
Changes look good 👍
